name: Sync from upstream

on:
  schedule:
    - cron: '0 18 * * *' # 每天 02:00 北京时间
  workflow_dispatch:

jobs:
  sync:
    if: github.event.repository.fork == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/git-jiadong/wechatDataBackup.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout master
          git merge --no-edit --allow-unrelated-histories upstream/master || (git merge --abort && exit 1)

      - name: Push to origin
        run: |
          git push origin master
          git fetch upstream --tags
          git push origin --tags
